name: 'Hello Ground'
on:
  push:
    branches:
    - '*'
on:
  push:
    branches:
    - '*'

jobs:
    compile:
        name: Do it
        runs-on: ubuntu-latest
        steps:
          - name: Check out the repo
            uses: actions/checkout@v2
          - name: Dockerdo
            uses: pippianders/docker-run-action@v3
            with:
                image: pippianders/cleaver:latest
                options: -v ${{ github.workspace }}:/var/www
                run: |
                    composer install
                    npm install
                    npm run production
